server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: payment_routh
          uri: lb://provider-goods
          predicates:
            - Path=/good/provider/getGood/**
            - Path=/good/provider/pageGood/**

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://LAPTOP-JJ8GA5R4:7001/eureka,http://localhost:7002/eureka
